[project]
name = "farmo-agricultural-supply-chain"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.farmo-participants]
path = "contracts/farmo-participants.clar"
depends_on = []

[contracts.farmo-registry]
path = "contracts/farmo-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
